const puzzles={easy:'530070000600195000098000060800060003400803001700020006060000280000419005000080079',medium:'000260701680070090190004500820100040004602900050003028009300074040050036703018000',hard:'000000907000420180000705026100904000050000040000507009920108000034059000507000000'};
const solutions={easy:'534678912672195348198342567859761423426853791713924856961537284287419635345286179',medium:'435269781682571493197834562826195347374682915951743628519326874248957136763418259',hard:'483651927659423187271785326168934752752816493394572619926148375834269571517397268'};
const relics=[['Clear Mind','First mistake on each floor deals no damage.','◈'],['Lucky Seven','Every seventh correct cell earns a coin.','✦'],['Glass Key','Hints reveal two cells, but cost one vitality.','◇'],['Iron Nerve','The first incorrect guess is erased for free.','⬡']];
const boardEl=document.querySelector('#board'),timerEl=document.querySelector('#timer'),toastEl=document.querySelector('#toast'),mobileEntry=document.querySelector('#mobileEntry');
let difficulty='medium',puzzle='',solution='',values=[],notes=[],treasures=new Set(),selected=-1,damage=0,seconds=0,floor=1,coins=0,relic=relics[0],timer,correct=0,combo=0,guardianMax=45;
const row=i=>Math.floor(i/9),col=i=>i%9,formatTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function startRun(){floor=1;damage=0;coins=0;relic=relics[Math.floor(Math.random()*relics.length)];startFloor('medium');document.querySelector('#winModal').hidden=true}
function startFloor(level){difficulty=level;puzzle=puzzles[level];solution=solutions[level];values=puzzle.split('');notes=Array.from({length:81},()=>new Set());treasures=new Set(values.map((v,i)=>v==='0'?i:-1).filter(i=>i>=0).sort(()=>Math.random()-.5).slice(0,Math.max(3,6-floor)));selected=-1;correct=0;combo=0;guardianMax=values.filter(v=>v==='0').length;seconds=floor===1?0:seconds;clearInterval(timer);timer=setInterval(()=>{seconds++;timerEl.textContent=formatTime(seconds)},1000);render();updateRunUI()}
function updateRunUI(){document.querySelector('#floor').textContent=floor;document.querySelector('#hearts').textContent='♥'.repeat(Math.max(0,3-damage))+'♡'.repeat(Math.min(3,damage));document.querySelector('#coins').textContent=coins;document.querySelector('#relicName').textContent=relic[0];document.querySelector('#relicText').textContent=relic[1];document.querySelector('.relic-icon').textContent=relic[2];document.querySelector('#bestFloor').textContent=Math.max(floor,Number(localStorage.getItem('gridrun-best')||1));document.querySelector('#comboText').textContent=`Combo ×${Math.max(1,combo)}`;document.querySelector('#threatCount').textContent=`${guardianMax-correct} / ${guardianMax}`;document.querySelector('#threatBar').style.width=`${Math.max(0,(guardianMax-correct)/guardianMax*100)}%`;document.querySelector('#guardianText').textContent=floor>=4?'The Grid Warden':floor>=2?'The Red Herring':'The Blank Page';document.querySelectorAll('[data-difficulty]').forEach(b=>b.classList.toggle('active',b.dataset.difficulty===difficulty));document.querySelector('#statusText').textContent=`Floor ${floor} · ${difficulty==='hard'?'Cursed':difficulty==='easy'?'Quiet':'Standard'}`}
function render(){boardEl.innerHTML='';values.forEach((value,i)=>{const cell=document.createElement('button');cell.className='cell '+(puzzle[i]!=='0'?'given':'user');if(treasures.has(i))cell.classList.add('treasure');cell.dataset.index=i;cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',`Row ${row(i)+1}, column ${col(i)+1}${value==='0'?' empty':`, ${value}`}`);if(i===selected)cell.classList.add('selected');if(selected>=0&&(row(i)===row(selected)||col(i)===col(selected)||Math.floor(row(i)/3)===Math.floor(row(selected)/3)&&Math.floor(col(i)/3)===Math.floor(col(selected)/3)))cell.classList.add('related');if(selected>=0&&value!=='0'&&value===values[selected])cell.classList.add('same-number');if(value==='0'&&notes[i].size){const ns=document.createElement('div');ns.className='notes';[1,2,3,4,5,6,7,8,9].forEach(n=>{const s=document.createElement('span');s.textContent=notes[i].has(String(n))?n:'';ns.append(s)});cell.append(ns)}else cell.append(value==='0'?'':value);cell.addEventListener('click',()=>{selected=i;render();if(puzzle[i]==='0'){mobileEntry.value='';mobileEntry.focus()}});boardEl.append(cell)})}
function hit(){if(relic[0]==='Clear Mind'&&damage===0)return;damage++;updateRunUI();if(damage>=3){clearInterval(timer);document.querySelector('#modalEyebrow').textContent='RUN ENDED';document.querySelector('#modalTitle').textContent='The grid wins.';document.querySelector('#modalCopy').innerHTML='You reached floor <strong>'+floor+'</strong>. Every run teaches you something.';document.querySelector('#winModal').hidden=false}else showToast(`${3-damage} vitality remaining.`)}
function input(n){if(selected<0||puzzle[selected]!=='0')return;const val=String(n);if(solution[selected]!==val){combo=0;updateRunUI();if(relic[0]==='Iron Nerve'&&damage===0){showToast('Iron Nerve absorbed the hit.');relic=['Spent nerve','No more free mistakes this run.','—']}else hit();document.querySelector(`[data-index="${selected}"]`)?.classList.add('error');return}if(document.querySelector('#notesToggle').getAttribute('aria-pressed')==='true'){notes[selected].has(val)?notes[selected].delete(val):notes[selected].add(val)}else{values[selected]=val;notes[selected].clear();notes.forEach(n=>n.delete(val));correct++;combo++;if(treasures.has(selected)){treasures.delete(selected);coins+=3;showToast('Treasure found · +3 coins')}else if(combo%5===0){coins+=combo;showToast(`Combo ×${combo} · +${combo} coins`)}if(combo%9===0&&damage>0){damage--;showToast('Perfect runic line · vitality restored')}}updateRunUI();render();if(values.every((v,i)=>v===solution[i]))clearFloor()}
function clearFloor(){clearInterval(timer);coins+=floor;const next=floor+1;localStorage.setItem('gridrun-best',String(Math.max(next,Number(localStorage.getItem('gridrun-best')||1))));if(floor>=5){document.querySelector('#modalEyebrow').textContent='RUN COMPLETE';document.querySelector('#modalTitle').textContent='You escaped.';document.querySelector('#modalCopy').innerHTML='Five floors cleared with <strong>'+coins+' coins</strong> in '+formatTime(seconds)+'.';document.querySelector('#winModal').hidden=false;return}showToast(`Floor ${floor} cleared · +${floor} coins`);setTimeout(()=>{floor=next;const nextLevel=floor>=4?'hard':floor>=2?'medium':'easy';startFloor(nextLevel)},900)}
function erase(){if(selected>=0&&puzzle[selected]==='0'){values[selected]='0';notes[selected].clear();render()}}
function hint(){if(selected<0||puzzle[selected]!=='0')return;values[selected]=solution[selected];notes[selected].clear();render();showToast('A rune reveals the path.');if(values.every((v,i)=>v===solution[i]))clearFloor()}
function showToast(message){toastEl.textContent=message;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1600)}
mobileEntry.addEventListener('input',()=>{const digit=mobileEntry.value.match(/[1-9]/)?.[0];mobileEntry.value='';if(digit)input(digit)});mobileEntry.addEventListener('keydown',e=>{if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();erase()}});
document.querySelectorAll('[data-difficulty]').forEach(b=>b.addEventListener('click',()=>{difficulty=b.dataset.difficulty;startFloor(difficulty)}));document.querySelectorAll('#newGameButton,#newGameTop,#playAgain').forEach(b=>b.addEventListener('click',startRun));document.querySelector('#eraseButton').addEventListener('click',erase);document.querySelector('#hintButton').addEventListener('click',hint);document.querySelector('#notesToggle').addEventListener('click',e=>{const active=e.currentTarget.getAttribute('aria-pressed')==='true';e.currentTarget.setAttribute('aria-pressed',String(!active));showToast(!active?'Notes mode on':'Notes mode off')});document.addEventListener('keydown',e=>{if(e.target===mobileEntry)return;if(/^[1-9]$/.test(e.key))input(e.key);if(e.key.toLowerCase()==='e')erase();if(e.key.toLowerCase()==='n')document.querySelector('#notesToggle').click();if(e.key.toLowerCase()==='h')hint();if(e.key==='Backspace'||e.key==='Delete')erase()});document.querySelector('#dateLabel').textContent=new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date());startRun();
